---
repo-name: peripherals-netsuite
categories:
- CRM
display-name: NetSuite
manufacturer: Oracle Corporation
product: NetSuite
description: NetSuite is the leading integrated cloud business software suite, including business accounting, ERP, CRM and ecommerce software.